# Generated by Django 4.0.6 on 2022-07-14 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=150)),
                ('isim', models.CharField(max_length=150)),
                ('aciklama', models.TextField(max_length=5000)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('güncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('yayinlanma_tarihi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum_sahibi', models.CharField(max_length=150)),
                ('yorum', models.TextField(max_length=1000)),
                ('yaratilma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('güncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('degerlendirme', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kitaplar.kitap')),
            ],
        ),
    ]
